export { Registration, loginForm } from './Registration'
export { Dashboard, initCharts, initFilters } from './Dashboard'
export { Dropdown, createDropdown, priorityDropdown } from './Dropdown'
export { input } from '../UI/Input'
export { loginFormHandler } from './Registration'
export { initBot } from './Support/initBot'
